stages:
  - Init
  - Validate
  # - Build and Push
  # - Staging Plan
  # - Staging Apply
  # - Production Plan
  # - Production Apply
  - Plan
  - Apply
  - Destroy

Terraform Init:
  stage: Init
  script:
    - terraform init
  tags:
    - devops
  only:
    - terraform  

  # rules:
  #   - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(main|production)$/ || $CI_COMMIT_BRANCH =~ /^(main|production)$/'

Validate Terraform:
  stage: Validate
  script:
    - terraform validate
  tags:
    - devops
  only:
    - terraform 
  # rules:
  #   - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(main|production)$/ || $CI_COMMIT_BRANCH =~ /^(main|production)$/'

Terraofrom Plan:
  stage: Plan
  script:
    - terraform plan
  tags:
    - devops
  only:
    - terraform 
  #   - echo "Run Terraform Plan for Production"
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "production"'

# Terraform Apply:
#   stage: Apply
#   script:
#     - terraform apply
#   tags:
#     - devops
#   only:
#     - terraform 
  #   - echo "Run Terraform Apply for Production"
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "production"'
  #     when: manual

# Terraform Destroy:
#   stage: Destroy
#   script:
#     - terraform destroy
#   tags:
#     - devops
#   only:
#     - terraform 
#   #   - echo "Run Terraform Destroy for Production"
#   # rules:
#   #   - if: '$CI_COMMIT_BRANCH == "production"'
#   #     when: manual
