stages:
  - Init
  - Validate
  - Plan
  - Apply
  - Destroy

Terraform Init:
  stage: Init
  script:
    - terraform init
  tags:
    - devops
  only:
    - terraform  
Validate Terraform:
  stage: Validate
  script:
    - terraform validate
  tags:
    - devops
  only:
    - terraform 
Terraofrom Plan:
  stage: Plan
  script:
    - terraform plan
  tags:
    - devops
  only:
    - terraform
