steps:
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['clean','install','-DskipTests']
# logsBucket: 'gs://build'
serviceAccount: '200307957970@cloudbuild.gserviceaccount.com'
options:
  logging: NONE
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gokul-usermgmt-webapp:1.2.0"]
#logsBucket: 'gs://build'
#serviceAccount: '200307957970@cloudbuild.gserviceaccount.com'
# options:
#   logging: CLOUD_LOGGING_ONLY
#   args: ['clean','install','-DskipTests']
