steps:
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['clean','install','-DskipTests']
# options:
#    logging: NONE
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gokul-usermgmt-webapp:1.2.0"]
# - name: 'bash'
#   args: ['echo', 'Hello world!']
# logsBucket: 'gs://build'
# options:
#   logging: GCS_ONLY
