steps:
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['clean', 'install','-Dmaven.test.skip=true']
options:
  logging: GCS_ONLY
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/project-id/gokul-usermgmt-webapp:1.2.0"]
