apiVersion: v1
kind: ConfigMap
metadata:
  namespace: production
  name: usermanagement-dbcreation-script
data: 
  mysql_usermgmt.sql: |-
    DROP DATABASE IF EXISTS webappdb;
    CREATE DATABASE webappdb; 
# to store and recall non-confidential data from configmap file to deployment or other k8s yaml file
# mysql_usrmgmt.sql file used to drop if already webappdb avail or it will create the db
