apiVersion: v1
kind: Service
metadata: 
  namespace: production
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql 
  ports: 
    - port: 3306  
# Mysql service mapped with clusterIP    
