apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-password
type: Opaque #password format changed base64 that's why here we used opaque
data:
  db-password: ZGJwYXNzd29yZDEx


# Builtin Type	                         Usage
# Opaque	                               arbitrary user-defined data
# kubernetes.io/service-account-token	   service account token
# kubernetes.io/dockercfg	serialized     ~/.dockercfg file
# kubernetes.io/dockerconfigjson	       serialized ~/.docker/config.json file
# kubernetes.io/basic-auth	             credentials for basic authentication
# kubernetes.io/ssh-auth                 credentials for SSH authentication
# kubernetes.io/tls	                     data for a TLS client or server
# bootstrap.kubernetes.io/token	         bootstrap token data


